// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// WQRADMMCPP
Rcpp::List WQRADMMCPP(arma::mat x, arma::vec y, arma::vec rep, double tau, bool intercept, String esttype, String corrtype, double rhoCQR, double rhoWQR, double eps, double epsw, int maxstep, int maxstepw);
RcppExport SEXP _WQRADMM_WQRADMMCPP(SEXP xSEXP, SEXP ySEXP, SEXP repSEXP, SEXP tauSEXP, SEXP interceptSEXP, SEXP esttypeSEXP, SEXP corrtypeSEXP, SEXP rhoCQRSEXP, SEXP rhoWQRSEXP, SEXP epsSEXP, SEXP epswSEXP, SEXP maxstepSEXP, SEXP maxstepwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type rep(repSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< String >::type esttype(esttypeSEXP);
    Rcpp::traits::input_parameter< String >::type corrtype(corrtypeSEXP);
    Rcpp::traits::input_parameter< double >::type rhoCQR(rhoCQRSEXP);
    Rcpp::traits::input_parameter< double >::type rhoWQR(rhoWQRSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type epsw(epswSEXP);
    Rcpp::traits::input_parameter< int >::type maxstep(maxstepSEXP);
    Rcpp::traits::input_parameter< int >::type maxstepw(maxstepwSEXP);
    rcpp_result_gen = Rcpp::wrap(WQRADMMCPP(x, y, rep, tau, intercept, esttype, corrtype, rhoCQR, rhoWQR, eps, epsw, maxstep, maxstepw));
    return rcpp_result_gen;
END_RCPP
}
// paraWQRADMMCPP
Rcpp::List paraWQRADMMCPP(arma::mat x, arma::vec y, int K, arma::vec rep, double tau, bool intercept, String esttype, String corrtype, double rhoCQR, double rhoWQR, double eps, double epsw, int maxstep, int maxstepw);
RcppExport SEXP _WQRADMM_paraWQRADMMCPP(SEXP xSEXP, SEXP ySEXP, SEXP KSEXP, SEXP repSEXP, SEXP tauSEXP, SEXP interceptSEXP, SEXP esttypeSEXP, SEXP corrtypeSEXP, SEXP rhoCQRSEXP, SEXP rhoWQRSEXP, SEXP epsSEXP, SEXP epswSEXP, SEXP maxstepSEXP, SEXP maxstepwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type rep(repSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< String >::type esttype(esttypeSEXP);
    Rcpp::traits::input_parameter< String >::type corrtype(corrtypeSEXP);
    Rcpp::traits::input_parameter< double >::type rhoCQR(rhoCQRSEXP);
    Rcpp::traits::input_parameter< double >::type rhoWQR(rhoWQRSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type epsw(epswSEXP);
    Rcpp::traits::input_parameter< int >::type maxstep(maxstepSEXP);
    Rcpp::traits::input_parameter< int >::type maxstepw(maxstepwSEXP);
    rcpp_result_gen = Rcpp::wrap(paraWQRADMMCPP(x, y, K, rep, tau, intercept, esttype, corrtype, rhoCQR, rhoWQR, eps, epsw, maxstep, maxstepw));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_WQRADMM_WQRADMMCPP", (DL_FUNC) &_WQRADMM_WQRADMMCPP, 13},
    {"_WQRADMM_paraWQRADMMCPP", (DL_FUNC) &_WQRADMM_paraWQRADMMCPP, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_WQRADMM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
