# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

WQRADMMCPP <- function(x, y, rep, tau, intercept, esttype, corrtype, rhoCQR, rhoWQR, eps, epsw, maxstep, maxstepw) {
    .Call('_WQRADMM_WQRADMMCPP', PACKAGE = 'WQRADMM', x, y, rep, tau, intercept, esttype, corrtype, rhoCQR, rhoWQR, eps, epsw, maxstep, maxstepw)
}

paraWQRADMMCPP <- function(x, y, K, rep, tau, intercept, esttype, corrtype, rhoCQR, rhoWQR, eps, epsw, maxstep, maxstepw) {
    .Call('_WQRADMM_paraWQRADMMCPP', PACKAGE = 'WQRADMM', x, y, K, rep, tau, intercept, esttype, corrtype, rhoCQR, rhoWQR, eps, epsw, maxstep, maxstepw)
}

