# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

WS <- function(x, y, rep, tau, betahat, intercept, corrtype = "ar1", epsw = 1e-06, maxstepw = 100) {
    .Call(`_WQRADMM_WS`, x, y, rep, tau, betahat, intercept, corrtype, epsw, maxstepw)
}

WQRADMM <- function(x, y, rep, tau, intercept, esttype, warmstart = TRUE, corrtype = "ar1", rhoCQR = 1, rhoWQR = 1, eps = 1e-04, epsw = 1e-06, maxstep = 5000L, maxstepw = 100L) {
    .Call(`_WQRADMM_WQRADMM`, x, y, rep, tau, intercept, esttype, warmstart, corrtype, rhoCQR, rhoWQR, eps, epsw, maxstep, maxstepw)
}

paraWQRADMM <- function(x, y, K, rep, tau, intercept, esttype, warmstart = TRUE, corrtype = "ar1", rhoCQR = 1, rhoWQR = 1, eps = 1e-04, epsw = 1e-06, maxstep = 5000L, maxstepw = 100L) {
    .Call(`_WQRADMM_paraWQRADMM`, x, y, K, rep, tau, intercept, esttype, warmstart, corrtype, rhoCQR, rhoWQR, eps, epsw, maxstep, maxstepw)
}

