# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

WQRADMM <- function(x, y, rep, tau, intercept, esttype, corrtype = "exchangeable", rho_CQR = 1, rho_WQR = 1, eps = 1e-04, epsw = 1e-06, maxstep = 1000L, maxstepw = 1000L) {
    .Call(`_WQRADMM_WQRADMM`, x, y, rep, tau, intercept, esttype, corrtype, rho_CQR, rho_WQR, eps, epsw, maxstep, maxstepw)
}

paraWQRADMM <- function(x, y, K, rep, tau, intercept, esttype, corrtype = "exchangeable", rho_CQR = 1, rho_WQR = 1, eps = 1e-04, epsw = 1e-06, maxstep = 1000L, maxstepw = 1000L) {
    .Call(`_WQRADMM_paraWQRADMM`, x, y, K, rep, tau, intercept, esttype, corrtype, rho_CQR, rho_WQR, eps, epsw, maxstep, maxstepw)
}

